[package]
name = "solicitantes"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["cdylib"]  # ¡ESTA LÍNEA ES IMPRESCINDIBLE!
[dependencies]
soroban-sdk = "22.0.7"
[profile.release]
opt-level = "z"
lto = true
panic = "abort"
